# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(related_name='actors', to='movies.Movie'),
        ),
    ]
