# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20171111_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='productor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.Productor'),
        ),
    ]
